blacklist mhi_pci
install mhi_pci /bin/true
blacklist mhi_uci
install mhi_uci /bin/true
blacklist mhi_net
install mhi_net /bin/true
blacklist wwan
install wwan /bin/true
blacklist wwan_mhi
install wwan_mhi /bin/true
blacklist fsm_dp
install fsm_dp /bin/true
