# SPDX-License-Identifier: GPL-2.0
# Copyright (C) 2021 Canonical Ltd
name: imx-kernel
type: kernel
build-base: core26
adopt-info: kernel
summary: The i.MX family Linux kernel
description: |
  This snap provides the kernel, modules, firmware, and initrd required to
  create an kernel snap the NXP i.MX family.

  The kernel and initrd are provided as a single universal kernel image file
  which is then booted by the managed assets created and owned by snapd.
  Generally, this snap would also provide the device tree files for the target
  hardware. However, in this case, that device tree is provided by the u-boot
  binary in our gadget snap. If we needed it here, we could likewise add that
  file to our UKI.

  ** Note that the license information for this snap is incomplete **
  Do your due diligence to ensure compliance with the licenses of the contents of this snap.

  This snapcraft.yaml is licensed under CC-BY-SA-4.0

  You can find any and all licenses for the contents of this snap at the following locations:

  kernel:             https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/resolute
  linux-firmware:     https://git.launchpad.net/ubuntu/+source/linux-firmware/tree/?h=applied/ubuntu/resolute

  Additional licenses can also be found within this snap in the licenses/ top-level directory.

grade: stable
confinement: strict

license: "GPL-2.0 AND GPL-3.0 AND CC-BY-SA-4.0"

platforms:
  arm64:
    build-on: [amd64, arm64]
    build-for: arm64

parts:
  # Provide the kernel.
  # Trimming any modules we know a priori to not be needed by the target device
  # can marginally reduce kernel snap size.
  kernel:
    plugin: kernel
    kernel-ubuntu-kconfigflavour: imx
    build-environment:
      - KERNEL_IMAGE: Image
      - PATH: "/usr/lib/ccache:${PATH}"
    override-build: |
      craftctl default
      craftctl set version=$(git --git-dir=${CRAFT_PROJECT_DIR}/.git describe --tags | cut -c 12-42 | sed 's/-snap$//')
    prime:
      - -vmlinuz*
      - -dtbs

  # Provide the initrd for Ubuntu Core.
  # The initrd includes important things such as snap-bootstrap which
  # orchestrates the entire Ubuntu Core installation process. The documentation
  # for this tool can be found here:
  # https://github.com/snapcore/snapd/blob/master/cmd/snap-bootstrap/README.md
  initrd:
    after:
      - firmware
      - kernel
    plugin: initrd
    initrd-firmware:
      - firmware/imx/sdma/sdma-imx7d.bin
      - firmware/regulatory.db
      - firmware/regulatory.db.p7s
    prime:
      - -initrd.img*

  firmware:
    after:
      - firmware-trim-tool
      - kernel
    plugin: nil
    stage-packages:
      - linux-firmware-misc
      - linux-firmware-qualcomm-wireless
      - wireless-regdb
    organize:
      lib/firmware: firmware
      usr/lib/firmware: firmware
    override-stage: |
      # do not re-run trim tool if already run
      fw_marker="${CRAFT_PART_INSTALL}/.firmware-trimmed"
      if [ ! -e "${fw_marker}" ]; then
        # Trim firmware
        "${CRAFT_STAGE}/trim-firmware" "${CRAFT_PART_INSTALL}" "${CRAFT_STAGE}"
        touch "${fw_marker}"
        craftctl default
      fi
    prime:
      - firmware

  firmware-trim-tool:
    plugin: dump
    source: https://git.launchpad.net/~ondrak/canonical-kernel-snaps
    source-branch: main
    source-depth: 1
    source-type: git
    stage:
      - trim-firmware
    prime:
      - -*

build-packages:
  - bison
  - ccache
  - cpio
  - device-tree-compiler
  - dpkg-dev
  - flex
  - gawk
  - libdw-dev
  - libfdt-dev
  - libssl-dev
  - pkgconf
  - python3-cryptography
  - python3-pycryptodome
  - python3-pyelftools
  - python3-serial
  - sbsigntool
  - u-boot-tools
  - uuid-dev
  - wget
  - on amd64:
    - gcc-aarch64-linux-gnu
  - on arm64:
    - gcc
